version: '3'

services:
  app:
    build: .
    environment:
      JAR_FILE: ${JAR_FILE:-libs/multiple-logout-example-0.1.0.jar}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    volumes:
      - "./build:/opt/app"
    ports:
      - "8080:8080"
    links:
      - redis
  redis:
    image: "redis:4-alpine"
